# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "lidq92"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/arxiv-daily.json'
json_gitpage_path: './docs/arxiv-daily-web.json'
json_wechat_path: './docs/arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
# topics: task/technique/dataset...
keywords:
    "Point Cloud Compression": 
        filters: ["Point Cloud Compression", 
                  "Point Cloud Coding", 
                  "Point Cloud Upsampling", 
                  "Point Cloud Geometry Compression",
                  "Point Cloud Geometry Coding",
                  "Point Cloud Super Resolution",
                  "Point Cloud Interpolation",
                  "Point Cloud Attribute Compression",
                  "Point Cloud Attribute Coding"]
    "Compression":
        filters: ["Compression", 
                  "Image Compression",
                  "Video Compression",
                  "Data Compression",
                  "Neural Compression",
                  "Network Compression",
                  "Image Coding",
                  "Video Coding"]
    "Quality Assessment":
        filters: ["Perceptual Quality",
                  "Quality Assessment",
                  "Visual Quality",
                  "Image Quality",
                  "Video Quality",
                  "Quality Evaluation",
                  "Quality Estimation",
                  "Quality Measurement"]
    "Super Resolution":
        filters: ["Super Resolution", 
                  "Super-Resolution",
                  "Upsampling",
                  "Interpolation"]
    "Remote Sensing":
        filters: ["Remote Sensing", 
                  "Hyperspectral", 
                  "Multispectral", 
                  "LiDAR",
                  "Satellite"]
